---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: quarkus-jvm-vpa
spec:
  # recommenders field can be unset when using the default recommender.
  # When using an alternative recommender, the alternative recommender's name
  # can be specified as the following in a list.
  # recommenders:
  #   - name: 'alternative'
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: quarkus-jvm
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
#        minAllowed:
#          cpu: 100m
#          memory: 50Mi
#        maxAllowed:
#          cpu: 1
#          memory: 500Mi
        controlledResources: ["cpu", "memory"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-jvm

spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-jvm
  template:
    metadata:
      labels:
        app: quarkus-jvm
    spec:
      containers:
        - name: code-with-quarkus-jvm
          image: quarkus/code-with-quarkus-jvm
          imagePullPolicy: IfNotPresent
#          command: ["./application","-Dquarkus.http.host=0.0.0.0"]
#          args: ["-c", "ng build --configuration=dev --prod && http-server dist/rbor-model-explorer"]
#          env:
#            - name: APP_ENV
#              value: dev
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-jvm
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: quarkus-jvm
